name: Flutter build

on:
  push:
    branches:
      - main
      - develop
    tags:
      - stable
      - nightly
  release:
    types: [published]
  pull_request:

permissions:
  contents: read

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-ipa:
    name: build-ipa (iOS)
    runs-on: macos-26
    defaults:
      run:
        working-directory: app
    env:
      BUILD_FLAVOR: ${{ (github.ref == 'refs/tags/stable' || (github.event_name == 'release' && !github.event.release.prerelease)) && 'production' || 'nightly' }}

    steps:
      - name: ⬆️ Checkout
        uses: actions/checkout@v7

      - name: 🦀 Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rust-src-dir: app

      - name: 🐦 Setup Flutter
        uses: subosito/flutter-action@v2.23.0
        with:
          flutter-version-file: app/pubspec.yaml
          cache: true

      - name: 📦 Get dependencies
        run: flutter pub get

      - name: 🏭 Build
        run: |
          flutter build ios \
            --release \
            --no-codesign \
            -v \
            --dart-define=flavor=${{ env.BUILD_FLAVOR }}

      - name: 📦 Package IPA
        run: |
          cd build/ios/iphoneos
          rm -rf Payload
          mkdir Payload
          cp -R Runner.app Payload/
          rm -f linwood-butterfly-ios.ipa
          zip -vr linwood-butterfly-ios.ipa Payload/

      - name: 📤 Upload IPA
        uses: actions/upload-artifact@v7
        with:
          name: ipa-build
          path: app/build/ios/iphoneos/linwood-butterfly-ios.ipa
          compression-level: 0
