name: Build iOS ipa

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Flutter iOS App
    runs-on: macos-latest
    steps:
      # Step 1: Check out the code
      - uses: actions/checkout@v2
      
      # Step 2: Prepare ExportOptions.plist
      - name: Create plist file
        run: |
          cat <<EOF > ios/ExportOptions.plist
          ${{ secrets.EXPORT_OPTION_PLIST }}
          EOF

      # Step 3: Build the iOS app with Flutter
      - name: iOS Application Building...
        uses: cedvdb/action-flutter-build-ios@v1
        with:
          build-cmd: flutter build ipa --export-options-plist=ios/ExportOptions.plist
          certificate-base64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          certificate-password: ${{ secrets.P12_PASSWORD }}
          provisioning-profile-base64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}

      # Step 4: Upload the IPA file as an artifact
      - name: Upload Artifact - IPA File
        uses: actions/upload-artifact@{latest}
        with:
          name: iOS-IPA
          path: build/ios/ipa/*.ipa
